# Generated by Django 3.1.4 on 2021-01-06 12:14

from django.db import migrations
import django_fsm


class Migration(migrations.Migration):

    dependencies = [
        ('bank', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transaction',
            name='status',
        ),
        migrations.AddField(
            model_name='transaction',
            name='state',
            field=django_fsm.FSMField(choices=[('in analysis', 'in analysis'), ('paid', 'paid'), ('refunded', 'refunded'), ('dispute', 'dispute'), ('failed', 'failed')], default=('in analysis', 'in analysis'), max_length=50),
        ),
    ]
