# Generated by Django 3.1.4 on 2021-01-06 15:53

from django.db import migrations
import django_fsm


class Migration(migrations.Migration):

    dependencies = [
        ('bank', '0003_auto_20210106_1247'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='state',
            field=django_fsm.FSMField(choices=[(0, 'in analysis'), (1, 'paid'), (2, 'refunded'), (3, 'dispute'), (4, 'failed')], default=(0, 'in analysis'), max_length=50, protected=True),
        ),
    ]
