# Generated by Django 3.1.4 on 2021-01-06 17:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bank', '0004_auto_20210106_1253'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transaction',
            name='state',
        ),
    ]
